name: "push-to-main"
on:
  push:
    branches:
      - main
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - run: yarn && yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(needs.one.outputs) }}
