name: "push-to-main"
on:
  push:
    branches:
      - main
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - id: release
        run: |
          yarn
          yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      new-release-version: ${{ steps.release.outputs.new-release-version }}
  two:
    needs: one
    if: needs.one.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.one.outputs.new-release-version }}
